displayName=Gauntlet Banked Xp
author=charredgrass
description=Tracks the amount of XP banked from Gauntlet rewards
tags=gauntlet
plugins=com.github.charredgrass.gauntletbankedxp.GauntletBankedXpPlugin